import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Needed for catppuccin theme:
[env]
TERM = "xterm-256color"

[window]
title = "Terminal"
class = { instance = "Alacritty", general = "Alacritty" }

[font]
#size = 16.0
size = 13.0
