[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Needed for catppuccin theme:
[env]
TERM = "xterm-256color"

[window]
title = "Terminal"
class = { instance = "Alacritty", general = "Alacritty" }

[font]
size = 13.0
[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
    { key = "PageUp", action = "ScrollLineUp" },
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp"},
    { key = "PageDown", action = "ScrollLineDown" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown"}
]
