# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:133.0) Gecko/20100101 Firefox/133.0', 'https://accounts.google.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/lucas/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///home/lucas/.local/share/qutebrowser/userscripts/*')


# Own settings:
# Dark mode:
# config.set('colors.webpage.darkmode.enabled', True)
config.set("colors.webpage.preferred_color_scheme", "dark")
import catppuccin
catppuccin.setup(c, 'latte', True)

config.set('fonts.default_size', '13pt')

config.bind(',p', 'spawn --userscript qute-pass --dmenu-invocation tofi')
config.bind(',P', 'spawn --userscript qute-pass --password-only --dmenu-invocation "tofi"')
# TODO: To get default binds and reconfigure them to colemak look at qute://help/settings.html#bindings.default
# config.set('tabs.position', 'left')
config.bind(',m', 'spawn umpv {url}')
config.bind(',M', 'hint links spawn mpv {hint-url}')
config.bind(';M', 'hint --rapid links spawn mpv {hint-url}')

config.set('auto_save.session', True)               # Keep Tabs
config.set('content.blocking.method', 'both')       # Block ads and trackers
c.content.blocking.adblock.lists = [ 'https://easylist.to/easylist/easylist.txt', 'https://easylist.to/easylist/easyprivacy.txt', 'https://easylist.to/easylistgermany/easylistgermany.txt', 'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt', 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt', ] # general adblocking # tracker blocking # german specific adblocking # quickly evolving list against ads that try to circumvent adblocking # prevent messages about disabling adblockers
# do not use the easycookielist, as it allows some cookies that it deems necessary instead of just hiding banners or rejecting all
config.set('content.cookies.accept', 'no-3rdparty') # Privacy
config.set('scrolling.smooth', True)
config.set('url.default_page', 'https://qwant.com')

config.set('content.pdfjs', True) # To open pdfs in browser automatically without prompt, see https://github.com/qutebrowser/qutebrowser/discussions/7073

# In qute, "a" and "e" are not bound, making remapping to gallium very easy, since "h" just stays where it is (shifted one to right from querty). So I just have to remap the movements, and their capitals, and i for inserting into field to k (see below)
# hjkl -> haei
# aei -> ljk : a zu l weil leicht erreichbar um in insert mode zu wechseln, e zu j weil e nicht so oft gebraucht wird, und j ist schwer zu erreichen, i zu k weil i für insert mode und leicht zu erreichen, und auch in vim wichtig für diw zum Beispiel

config.bind('a', 'scroll down')
config.bind('e', 'scroll up')
config.bind('i', 'scroll right')
config.bind('A', 'tab-next')
config.bind('gA', 'tab-move +')
config.bind('E', 'tab-prev')
config.bind('gI', 'tab-move -')
config.bind('I', 'forward')

config.bind('l', 'mode-enter insert')


# Search engines:
# use these by typing e.g. o for open, then "g testquery", so the command is "open -t g testquery". One could also add e.g. "!" in front of the letters to differentiate from letter searches, but in practice this never interferes
c.url.searchengines = {
    'DEFAULT':  'https://qwant.com/search?hl=en&q={}',
    'g':       'https://google.com/search?udm=14&q={}', # Google without ai and such
    'gh':      'https://github.com/search?o=desc&q={}&s=stars',
    'm':       'https://www.google.com/maps/search/{}',
    'w':       'https://en.wikipedia.org/wiki/{}',
    'mc':       'https://minecraft.wiki/w/{}',
}

config.bind(',t', 'spawn -o sh -c "curl --silent --show-error {url} | pandoc -f html -t plain"')

# config.bind(
#     ',t',
#     'spawn sh -c "tmp=/tmp/qute-cleaned.html; '
#     'curl -Ls {url} '
#     '| pandoc -f html -t html5 --lua-filter ~/.config/qutebrowser/filters/noimages.lua '
#     '> $tmp; '
#     'qutebrowser :open file://$tmp"'
# )
